latency-wait: "{{cookiecutter.latency_wait}}"
use-use-conda: {{cookiecutter.use_conda}}
keep-going: False
restart-times: 0
cluster: "qsub-submit.py"
cluster-status: "qsub-status.py"
jobscript: "qsub-jobscript.sh"
local-cores: 1
jobs: 20
cores: 40
conda-base-path: {{cookiecutter.conda_base_path}}
cache: {{cookiecutter.use_cache}}
